#!/bin/bash
AddPackage breeze-grub
AddPackage kdegraphics-thumbnailers
AddPackage kdenetwork-filesharing
AddPackage kimageformats
AddPackage noto-fonts
AddPackage noto-fonts-cjk
AddPackage noto-fonts-emoji
AddPackage print-manager
AddPackage sddm
AddPackage spectacle
AddPackage ttf-liberation
AddPackage xdg-desktop-portal
AddPackageGroup plasma
RemovePackage archlinux-appstream-data
RemovePackage bluedevil
RemovePackage discover
RemovePackage plasma-disks
RemovePackage plasma-firewall
RemovePackage plasma-thunderbolt
RemovePackage plasma-vault
